# Generated by Django 5.2.8 on 2026-01-29 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azkar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fajr', models.BooleanField(default=False)),
                ('dhuhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('taraweeh', models.BooleanField(default=False)),
                ('fasting', models.BooleanField(default=False)),
                ('sunnah_fajr', models.BooleanField(default=False)),
                ('sunnah_dhuhr', models.BooleanField(default=False)),
                ('sunnah_maghrib', models.BooleanField(default=False)),
                ('sunnah_isha', models.BooleanField(default=False)),
                ('quran_pages', models.IntegerField(default=0)),
                ('daily_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuranProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages_read', models.IntegerField(default=0)),
                ('completed_khatmas', models.IntegerField(default=0)),
                ('current_khatma_pages', models.IntegerField(default=0)),
                ('reward_given_for_current_khatma', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAzkarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azkar_status', to='points.dailyactivity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azkar.azkarcategory')),
            ],
            options={
                'unique_together': {('activity', 'category')},
            },
        ),
    ]
