# Generated by Django 5.2.8 on 2026-02-06 23:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azkar', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('fajr', models.BooleanField(default=False)),
                ('dhuhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('taraweeh', models.BooleanField(default=False)),
                ('fasting', models.BooleanField(default=False)),
                ('sunnah_fajr', models.BooleanField(default=False)),
                ('sunnah_dhuhr', models.BooleanField(default=False)),
                ('sunnah_maghrib', models.BooleanField(default=False)),
                ('sunnah_isha', models.BooleanField(default=False)),
                ('quran_pages', models.IntegerField(default=0)),
                ('daily_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OfflinePointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('prayer', 'Prayer'), ('fasting', 'Fasting'), ('quran', 'Quran'), ('azkar', 'Azkar'), ('sunnah', 'Sunnah'), ('taraweeh', 'Taraweeh')], max_length=20)),
                ('points', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuranProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages_read', models.IntegerField(default=0)),
                ('completed_khatmas', models.IntegerField(default=0)),
                ('current_khatma_pages', models.IntegerField(default=0)),
                ('reward_given_for_current_khatma', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم المكافأة الظاهر للطفل', max_length=100)),
                ('description', models.TextField(blank=True, help_text='وصف المكافأة')),
                ('type', models.CharField(choices=[('video', 'Video'), ('badge', 'Badge'), ('sticker', 'Sticker'), ('content', 'Extra Content')], max_length=20)),
                ('cost_points', models.PositiveIntegerField(help_text='عدد النقاط المطلوبة لشراء المكافأة')),
                ('is_active', models.BooleanField(default=True, help_text='هل المكافأة متاحة حالياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAzkarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azkar_status', to='points.dailyactivity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azkar.azkarcategory')),
            ],
            options={
                'unique_together': {('activity', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='points.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reward',
                'verbose_name_plural': 'User Rewards',
                'unique_together': {('user', 'reward')},
            },
        ),
    ]
