# Generated by Django 5.2.8 on 2026-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='points_from_exams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='points_spent_on_videos',
            field=models.IntegerField(default=0),
        ),
    ]
