# Generated by Django 5.2.8 on 2026-02-05 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('prayer', 'Prayer'), ('fasting', 'Fasting'), ('quran', 'Quran'), ('azkar', 'Azkar'), ('sunnah', 'Sunnah'), ('taraweeh', 'Taraweeh')], max_length=20)),
                ('points', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
