# Generated by Django 5.2.8 on 2026-02-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_userpoints_points_from_exams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='khatma_reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
