# Generated by Django 5.2.8 on 2025-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('child', 'Child')], default='child', max_length=10)),
            ],
        ),
    ]
