# Generated by Django 5.2.8 on 2026-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('child', 'Child')], max_length=10),
        ),
    ]
