# Generated by Django 5.2.8 on 2026-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
