# Generated by Django 5.2.8 on 2026-02-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('child', 'Child')], default='child', max_length=10),
        ),
    ]
