# Generated by Django 5.2.8 on 2026-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('child', 'Child'), ('admin', 'Admin')], default='child', max_length=10),
        ),
    ]
